version: "3.1"
services:
  redis:
    build:
      context: phpdocker/php-fpm
    container_name: fo-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    networks:
      - default
      - mallcomm-network

  webserver:
    image: nginx:alpine
    container_name: fo-webserver
    restart: unless-stopped
    working_dir: /application:consistent
    volumes:
      - .:/application
      - ./phpdocker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - ${FO_PORT}:80

  php-fpm:
    build:
      context: phpdocker/php-fpm
      args:
        - WITH_XDEBUG=true
    env_file:
      - phpdocker/php-fpm/.env
    container_name: fo-php-fpm
    restart: unless-stopped
    working_dir: /application
    depends_on:
      - telescope
    volumes:
      - .:/application:consistent
      - ./phpdocker/php-fpm/php-ini-overrides.ini:/etc/php/7.4/fpm/conf.d/99-overrides.ini
    networks:
      - default
      - researchfish-network

networks:
  default:
  researchfish-network:
    external: true

# Volumes
volumes:
  redis-data:
